#!/usr/bin/env ruby
require File.expand_path('../../utils/cacher', __FILE__)

class Casher
  attr_reader :cacher
  def initialize
    @cacher = ::Vx::Citool::Utils::Cacher.new(ENV['CASHER_DIR'] || "/opt/vexor/cache")
  end

  def run(command, *arguments)
    raise "unknown command" unless %w[fetch add push].include? command
    cacher.public_send(command, *arguments)
  end

end

Casher.new.run(*ARGV) if $0 == __FILE__
